CREATE TABLE Principal
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    age  int CHECK (age > 18)
);

CREATE TABLE School
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_number int        NOT NULL,
    principal_id  int UNIQUE REFERENCES Principal (id) ON DELETE SET NULL
);


INSERT INTO Principal(name, age)
VALUES ('Bob', 28);
INSERT INTO Principal(name, age)
VALUES ('Tom', 35);
INSERT INTO Principal(name, age)
VALUES ('Katy', 39);
INSERT INTO Principal(name, age)
VALUES ('Alice', 45);

INSERT INTO School(school_number, principal_id)
VALUES (7, 3);
INSERT INTO School(school_number, principal_id)
VALUES (131, 1);
INSERT INTO School(school_number, principal_id)
VALUES (18, 2);
INSERT INTO School(school_number, principal_id)
VALUES (39, 4);